### PR TITLE
README: Proofreading, markup [ci skip]

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR is a documentation polishing change.

Language, markup, formatting.

### CODE REVIEW

**Comment by infoduv** [comment]
This PR is a documentation polishing change by olleolleolle.

Language, markup, formatting.

**Comment by olleolleolle** [comment]
Oh, did you change your mind about merging the changes?

**Comment by infoduv** [comment]
No !  I'be probably made a mistake....

**Comment by infoduv** [comment]
Much better now :-)

**Pull request merged**
